### ISSUE TITLE
User changing speed of becoming thirsty

### ISSUE THREAD

**Issue by Golutazem** [NathanSalapat/drinks#10]
This request is for a way for the user to change the speed at which the player becomes thirsty. The current rate of becoming thirsty is impractically fast.
This could be based on the speed at which the player becomes hungry, such as making the player become thirsty twice as fast as he becomes hungry.

**Comment by NathanSalapat** [comment]
This mod doesn't control thirst, for that look to this mod, https://github.com/bendeutsch/minetest-thirsty
The drinks just replenish hydration if the thirst mod is running.
