### ISSUE TITLE
Pineapple of Farming Redo

### ISSUE THREAD

**Issue by Golutazem** [NathanSalapat/drinks#9]
The pineapple of Farming Redo is not squeezable.
Is there a good way for the user to see the HDX texture when using that pack?
https://gitlab.com/VanessaE/hdx-512/-/blob/master/farming_pineapple_juice.png
The only other juice in HDX is farming_carrot_juice.png
Or maybe an overlay of the vessels_drinking_glass.png can be done.

**Comment by Golutazem** [comment]
I tried it again with everything updated and it worked.
--except using the graphic from HDX.

**Comment by NathanSalapat** [comment]
You'd need to rename the textures from the HDX texture pack to support the mod. The glass would be drinks_drinking_glass.png and the contents are drawn as an overlay with the texture drinks_glass_contents.png
